import "./globals.css";
import Provider from "./Provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";

export const metadata = {
  title: "FindMyPG",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // path relative to /public
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClerkProvider>
          <Provider>
          <Toaster
            position="top-right"
            closeButton
            expand={false}
            duration={3000}
            offset={{ top: 90, right: 20 }} // 👈 moves it down 70px and right 30px
          />
            {children}
          </Provider>
        </ClerkProvider>
      </body>
    </html>
  );
}

